- README.md
- common/fips202.c
This fixes the incorrect cshake implementation by properly initializing the state.
> Fix CSHAKE

- README.md
- crypto_kem/kindi256342/ref/core.c
- crypto_kem/kindi256342/ref/core.h
- crypto_kem/kindi256342/ref/gen_randomness.c
- crypto_kem/kindi256342/ref/gen_randomness.h
- crypto_kem/kindi256342/ref/kem.c
- crypto_kem/kindi256342/ref/poly.c
- crypto_kem/kindi256342/ref/poly.h
I've refactored kindi to use local stack space instead of malloc.
The performance gain is quite huge.
This makes pqm4 `malloc`/`memalign`/`calloc`/`free` free. 
For future PRs we should enforce that as well.
> Refactor kindi256342 to not use dynamic memory allocations 

- README.md
We've noticed some significant cycle count variations for different versions of gcc. 
The previous benchmarks were unfortunately not all done using the same compiler version :( 
I've redone all the benchmarks with the most recent arm-none-eabi-gcc (8.2.0) and toolchain on Arch. I do not expect any gcc updates soon - so these numbers should stay stable for a while. 
I would welcome someone benchmarking this with an earlier gcc version.
> Updated benchmarks with arm-none-eabi-gcc 8.2.0

- benchmarks.py
- crypto_kem/speed.c
- crypto_kem/stack.c
This may occur e.g. when implementations make illegal use of the stack. It may be tempting to read/write beyond the stack pointer, but if measurement interrupts occurs this data gets overwritten.
> Check for incorrect keys when benchmarking KEMs

- Makefile
- README.md
- common/crypto_hash_sha512.h
- common/fips202.c
- common/fips202.h
- common/sha2.c
- common/sha2.h
- crypto_kem/ntru-kem-743/m4/poly.c
- crypto_kem/ntru-kem-743/ref/NTRUEncrypt.c
- crypto_kem/ntru-kem-743/ref/kem.c
- crypto_kem/ntru-kem-743/ref/poly.c
- crypto_kem/rlizard-1024-11/m4/RLizard.c
- crypto_kem/rlizard-1024-11/ref/RLizard.c
- crypto_kem/sntrup4591761/ref/dec.c
- crypto_kem/sntrup4591761/ref/enc.c
This renames `crypto_hash_sha512` to `sha512`. This makes it more consistent with the `fips202` functions. The header is renamed to `sha2.h`, such that it can also contain other SHA-2 instances. In particular, SHA-384 is added as some NIST submissions use it. It uses the same SUPERCOP C implementation as SHA-512.
> Refactor crypto_hash_sha512 and add sha384

- crypto_kem/test.c
- crypto_sign/test.c
The reference implementation of rlizard assumed that the public key is located in memory directly after the secret key. This was not detected by our tests, since it was the case. 
To catch such weird implementations, I added some canaries before and behind all keys and messages and check if they have changed afterwards. 
This should break these implementations and will catch implementations writing out of bounds. 
For all schemes except sphincs and sike, I ran the test.py script. For those two I did a single test execution. That is all passing - so we probably have no implementations writing out of bounds.
> Detect implementations writing out of bounds

- crypto_kem/kindi256342/m4/mult_notoom_256_16.s
- crypto_kem/ntru-kem-743/m4/mult_toom4_743_12.s
- crypto_kem/ntruhrss701/m4/mult_toom4_701_11.s
- crypto_kem/rlizard-1024-11/m4/mult_toom4_1024_16.s
- crypto_kem/saber/m4/mult_toom4_256_16.s
This imports the outcome of mupq/polymul-z2mx-m4#1 into pqm4.
I haven't re-benchmarked and edited `README.md` yet as we might want to make changes in #36 that affect cycle counts, so let's leave this open for a bit.
> Word-align the address of polymul_asm

- Makefile
- stm32f405x6.ld
By not using SRAM2 we get more consistent benchmarks since SRAM2 seems to slow
down memory accesses. This lead to schemes that are wasteful with stack
(i.e., overflowing the 16 KiB SRAM2 into SRAM1) were faster.
> Shrink RAM from 128 KiB to 112 KiB

- README.md
- benchmarks.csv
- benchmarks.md
I benchmarked only 1 execution. Could do more, but that'll take a while.
This updates `mupq` to `0181f7c5aced3c31c8b5474ac805636c388115cf`, but that also includes LAC. So it's easier to first benchmark and add LAC and only then merge this.
Fixes #50.
> Add SIKEp{434,503,610,751}

- README.md
- benchmarks.csv
- benchmarks.md
- interface.py
This adds SPHINCS+ benchmarks based on the reference code currently in pqclean.
> Add SPHINCS+ benchmarks

- README.md
- crypto_kem/kyber768/m4/symmetric-fips202.c
- crypto_kem/kyber768/m4/symmetric.h
- crypto_kem/newhope1024cca/m4/poly.c
- crypto_kem/newhope1024cpa/m4/poly.c
- crypto_sign/dilithium/m4/poly.c
- crypto_sign/dilithium/m4/sign.c
PQClean introduced a different API for hashing with an opaque state struct. This PR ports that into pqm4 and updates the relevant schemes to use that API.
I assume that the impact on benchmarks is zero or negligible.
This resolves #88.
> Update mupq/pqclean and port the opaque structs for the hashing API

- common/aes.S
Passing a pointer to an address that is not a multiple of 4 bytes will incur a minor performance penalty compared to aligned pointers. It's only a couple of cycles and it is better than hanging completely, as was the case before. To aligned pointers, there is no speed difference. Only a slightly larger code size, but it's all quite negligible.
Fixes #90.
> Allow AES to be called with non-aligned pointers

- Makefile
- benchmarks.csv
- benchmarks.md
Fixes #64.
This adds `ref` and `opt` implementations for `{baby,mama,papa}bear(-ephemeral)`.
> Add ThreeBears

- crypto_kem/kyber768/m4/fastntt.S
This replaces mov with movw for large constants in Kyber
Newer compilers manage to detect this automatically and use movw instead of mov, but it throws errors on older ones (e.g., on arm-none-abi-gcc 6.3.1).
> Fix Kyber assembly for older compilers

- Makefile
In #105 an issue was encountered with `sed -r`. This is a GNU-specific option to enable ERE, which may be called `-E` with `sed` in BSD/macOS. While GNU `sed` also supports `-E` (not sure which versions), we may as well completely avoid all of this by sticking to POSIX BRE.
This expression doesn't match exactly the same, but I believe it should work everywhere.
> Don't use any sed flags

- common/hal-stm32f4.c
`hal_get_time()` gave wrong values if the SysTick counter reached 0 between reading `overflowcnt` and calling `systick_get_value()`. This behavior is now addressed by retrying if that happens. Thanks to djb for pointing that out to us.
The reset value is also increased to the maximum of 2^24-1, such that there is less overhead from the interrupt handler, and overflowcnt is marked `volatile` to ensure correctness.
> Fix hal_get_time()

- common/hal-stm32f4.c
The missing fields are initialized with default values following
the conventions of the predefined profiles from
<https://libopencm3.org/docs/latest/stm32f4/html/rcc_8c_source.html>.
I did not test this patch on the M4 hardware.
This PR resolved issue #117 .
> Add missing fields in benchmarkclock struct

- crypto_kem/r5nd-1kemcca-5d/m4/ct_util.c
- crypto_kem/r5nd-1kemcca-5d/m4/ct_util.h
Hello,
ref. https://github.com/r5embed/r5embed/commit/71929f9c0b706d8193dcb31ba1214372d38fdcbe
The two last parameters in definition of` ct_cmov()` were flipped. The conditional move is only used in `r5_cca_kem_decapsulate()`, line 99 of r5_cca_kem.c:
```c
ct_cmov(hash_in, sk + PARAMS_KAPPA_BYTES, PARAMS_KAPPA_BYTES, fail);
```
This didn't break applications but implication was that CCA was not really CCA. The NIST submitted code does not appear to have this bug.
Cheers,
- markku
> len and flag were flipped

- benchmarks.csv
- benchmarks.md
@leonbotros included the CCA ThreeBears in PQClean: https://github.com/PQClean/PQClean/pull/248 
This PR removes the ref implementations we had in mupq and updates the benchmarks. 
It got very slightly slower. 
It would be nice if we could also move the ephemeral bears to PQClean.
> Add benchmarks of clean ThreeBears

- README.md
- common/hal-stm32f4.c
As new is always better, I've updated libopencm3. 
In https://github.com/libopencm3/libopencm3/commit/ca6dcfbea137bd2145b4a7fbf24379f565f8280d libopencm3 slightly changed the clock setup so we need to adjust that as well.
As all changes are in the clock setup, this does not affect benchmark results at all.
> Update to the most recent version of libopencm3

- benchmarks.csv
- benchmarks.md
The ephemeral three bears got integrated into PQClean recently https://github.com/PQClean/PQClean/pull/262, and I've updated the benchmarks. 
They seem to be negligibly slower. 
This also includes some minor fixes in mupq: https://github.com/mupq/mupq/pull/39, https://github.com/mupq/mupq/pull/40, https://github.com/mupq/mupq/pull/41, https://github.com/mupq/mupq/pull/42.
> Take clean CPA three bears from PQClean

- crypto_kem/newhope1024cca/m4/verify.c
- crypto_kem/newhope1024cca/m4/verify.h
- crypto_kem/newhope1024cpa/m4/verify.c
- crypto_kem/newhope1024cpa/m4/verify.h
- crypto_kem/newhope512cca/m4/verify.c
- crypto_kem/newhope512cca/m4/verify.h
- crypto_kem/newhope512cpa/m4/verify.c
- crypto_kem/newhope512cpa/m4/verify.h
#132 reported that the verify function is not actually doing what it is supposed to do.
As it is not used in the current pqm4 implementation of NewHope, I remove it here. 
For more details see #132.
The function needs to be fixed in PQClean: https://github.com/PQClean/PQClean/issues/269
> Remove unused NewHope verify function

- Makefile
- crypto_kem/ntrulpr761/m4f/Short_fromlist_asm_ntrulpr761.S
- crypto_kem/sntrup761/m4f/Decode_asm.S
- crypto_kem/sntrup761/m4f/Encode_asm.S
- crypto_kem/sntrup761/m4f/Rq_mult3_asm.S
- crypto_kem/sntrup761/m4f/Rq_redp.S
- crypto_kem/sntrup761/m4f/Short_fromlist_asm_sntrup761.S
- crypto_kem/sntrup761/m4f/jump4divsteps.S
- interface.py
Some older gcc versions complain about mov.w with constants being too large. See #164 
Changing those to movw fixes this.
> Fix ntruprime implementations for old gcc versions

- crypto_sign/dilithium2/m4/packing.c
- crypto_sign/dilithium2/m4/packing.h
- crypto_sign/dilithium2/m4/params.h
- crypto_sign/dilithium2/m4/poly.c
- crypto_sign/dilithium2/m4/poly.h
- crypto_sign/dilithium2/m4/polyvec.c
- crypto_sign/dilithium2/m4/polyvec.h
- crypto_sign/dilithium2/m4/sign.c
- crypto_sign/dilithium2/m4/symmetric.h
- crypto_sign/dilithium2/m4/vector.s
Dilithium announced changes which result in new testvectors in https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/BjfjRMIdnhM. This pulls the changes from PQClean (PQClean/PQClean#373) and ports the changes to our M4 implementation. 
The performance impact is minimal (copying around a few more bytes and needing a couple more bytes of stack). I'll not run the benchmarks now.
> Port Dilithium 3.1 changes to M4 implementation

- interface.py
@rpls, could you include this change in your re-work of the build system? 
It will greatly decrease benchmarking time by running all iterations in a single binary. 
See https://github.com/mupq/mupq/pull/58
> adjust pqm4 to run multiple iterations in a single binary

- build_everything.py
- interface.py
The previous version of pqm4 had a build everything script that would spit out
all the binaries.
With the multiplatform pqm4, this is no longer needed. One can simply
`make -j4 PLATFORM=stm32f4discovery`
However, we currently still have a non-functional build_everything.py script
sitting around. I've fixed it, but we could also remove it.
Additionally, to allow users to simply run ./test.py, I added a default uart
device "/dev/ttyUSB0". The old pqm4 also assumed that serial device.
Right now pqm4 miserably fails without a --uart argument and a reasonable
error message.
> Restore build_everything.py and add default uart

- crypto_kem/sntrup761/m4f/kem.c
#195 reports that the Ciphertexts_diff_mask in kem.c of ntrup761/ntrulpr761 looks obviously wrong. 
I applied to the suggested patch.
The bug was introduced in #150 which integrated the code from https://eprint.iacr.org/2019/100.pdf.
> Fixes bug in ntrup761/ntrulpr761 decapssulation

- crypto_sign/dilithium2/m4/ntt.s
Closes #198
The Dilithium NTT code was previously licensed under GPL-3.0. The authors have agreed to license it under CC0 so that it is in line with the rest of the code.
> Change licensing for Dilithium NTT

- common/hal-opencm3.c
On my Raspberry Pi I often ran into the problem that the Pi would miss the
beginning of the serial output and then get stuck in an infinite loop trying
to reflash again and again.
By waiting a couple of hundred ms when starting up, this can be prevented.
For me this heavily improved reliability.
> Improve reliability of benchmarking scripts

- Makefile
- README.md
- common/hal-opencm3.c
- common/randombytes.c
- common/test.c
- crypto_kem/bikel1/m4f/bike_aes.h
- crypto_kem/bikel1/m4f/run_config.h
- crypto_kem/bikel1/m4f/sha.h
- crypto_kem/bikel3/m4f/bike_aes.h
- crypto_kem/bikel3/m4f/run_config.h
- crypto_kem/bikel3/m4f/sha.h
- interface.py
- ldscripts/devices.data
- ldscripts/nucleo-l4r5zi-ramtest.ld
- ldscripts/nucleo-l4r5zi.ld
- ldscripts/stm32f4discovery.ld
- mk/config.mk
- mk/mps2-an386.mk
- mk/nucleo-l4r5zi.mk
- mk/opencm3.mk
- mk/stm32f4discovery.mk
- st_nucleo_l4r5.cfg
This adds support for Nucleo-L4R5ZI board, a fairly large (in terms of 640KB of SRAM) Cortex-M4 based board. This also includes a memory timing test (used to determine the memory timings of the board), and a small fix for the `bikel{1,3}` source (they checked for `STM32F4` definition, which isn't defined for this or any other non STM32F4 board).
Maybe one point that needs discussion is the memory layout of the board. The board has three SRAMs, all in one continuous address space:
- SRAM1: 192KB
- SRAM2: 64KB
- SRAM3: 384KB
The memory timing test showed that the first SRAM1 block has slightly faster load timings. This is a similar situation as with the STM32F4-Discovery board: There, first SRAM block also has faster timings than the second one (maybe a general situation for the …
> Add support for Nucleo-L4R5ZI board

- crypto_kem/kyber512/m4/indcpa.c
- crypto_kem/kyber768/m4/indcpa.c
Fixes two minor bugs in matacc. They did (luckily) not actually result in wrong
outputs.
In the uniform sampling, we use 3 bytes to sample 2 coefficients. In
case the sampled coefficient is too large, we throw it away.
Once we sampled 256 coefficients it is possible that we still have one
coefficient left which needs to be discarded.
The check if we are at the end of a polynomial already was wrongly
implemented by checking for `ctr < KYBER_Q/4` rather than `ctr < KYBER_N/4`
in two places.
Luckily, it has no effect in both cases.
In the first, `ctr = KYBER_N/4` implies k=0 and hence the code does
nothing.
In the second, an additional Keccak squeeze is triggered, but the output
is never used.
This bug was introduced in https://github.com/mupq/pqm4/pull/172/commits/a1cb9e2f1d1ea344207f8502f25 …
> Fix minor bug in Kyber

- crypto_kem/kyber768-90s/m4fspeed/matacc.h
- crypto_kem/kyber768-90s/m4fspeed/matacc_asm.S
- crypto_kem/kyber768-90s/m4fstack/matacc.h
- crypto_kem/kyber768-90s/m4fstack/matacc_asm.S
- crypto_kem/kyber768/m4fspeed/matacc.h
- crypto_kem/kyber768/m4fspeed/matacc.i
- crypto_kem/kyber768/m4fspeed/matacc_asm.S
- crypto_kem/kyber768/m4fstack/matacc.h
- crypto_kem/kyber768/m4fstack/matacc.i
- crypto_kem/kyber768/m4fstack/matacc_asm.S
**in Kyber matacc assembly implementation:**
- changed floating-point registers from s(0-15) to s(16-31): registers from s0 to s15 can be overwritten by the called function
- changed s31 (s15) to s0 in kyberXXX-90s m4fspeed: floating point registers are usually saved in couples using the 64bit d registers
- instructed the C compiler to consider clobbered the used floating registers before calling the assembly code
- saved the r12 register before calling the C function in kyber m4fspeed matacc_asm.S and kyber m4fstack matacc.i
> Fix function call from assembly

- common/keccakf1600.S
Update of the Keccak permutation written ARMv7-M assembly for better performance on the Cortex-M4.
It should lead to a performance gain of about 20%, as summarized in https://eprint.iacr.org/2023/773.
Here I opted for the variant that omit explicit rotations for three-quarters of the rounds only, so that it has a limited impact on code size.
> Update Keccak-f[1600] implementation for better performance

- common/hal-mps2.c
- common/hal-opencm3.c
- common/test.c
Use the new stack spraying/checking API of the HAL. This adds a small test in the `boardtest.elf`, which for me returns an accurate result (400/800 bytes alocated on stack, measurement returns 400/800 bytes). Some random spot-checks of schemes return very similar values for stack usage (few bytes difference, might also be explained by newer compiler).
The implementations checks entire words instead of bytes, so the result will only be on word granularity, i.e., 4 bytes.
> Implement new stack measurement HAL API

- crypto_kem/kyber512/m4fspeed/poly.c
- crypto_kem/kyber512/m4fstack/poly.c
- crypto_kem/kyber768/m4fspeed/poly.c
- crypto_kem/kyber768/m4fstack/poly.c
This (partially) addresses https://github.com/mupq/pqm4/issues/319.
The function poly_tomsg from the reference implementation of Kyber (which was copied into the M4-optimized implementations) would result in a variable-time udiv instruction operating on secret data when compiled with gcc using -Os. I tried a couple of versions from gcc 11 to gcc 13, but did not see any difference.
This commit updates the m4-specific code to use the patch from https://github.com/pq-crystals/kyber/commit/dda29cc63af721981ee2c831cf00822e69be3220. Note that the code in PQClean has not yet been updated and hence the clean implementation within pqm4 is still vulnerable.
> Update Kyber poly_tomsg to fix timing leak (w/ -Os)

- common/hal-opencm3.c
- interface.py
Update hal setup for stm32f415 and update interface.py platform_memory to handle stm32f415.
This should provide total support for stm32f415 as discussed in #258.
> Platform support for stm32f415

- .github/workflows/main.yml
- mk/mps2-an386.mk
We could use the Github Actions to enable some minimal form of contiouus integration. The goal would be to build all schemes for the simulated platform, to at least ensure that everything builds.
> Github continuous integration

- Makefile
- README.md
- benchmarks.py
- build_everything.py
- common/aes.c
- common/aes.h
- common/hal-mps2.c
- common/hal-opencm3.c
- common/keccaktest.c
- common/randombytes.c
- common/test.c
- convert_benchmarks.py
- interface.py
- mk/config.mk
- mk/crypto.mk
- mk/cw308t-stm32f3.mk
- mk/cw308t-stm32f415.mk
- mk/mps2-an386.mk
- mk/nucleo-l476rg.mk
- mk/nucleo-l4r5zi.mk
- mk/opencm3.mk
- mk/stm32f4discovery.mk
- mk/tests.mk
- st_nucleo_l4r5.cfg
- test.py
- testvectors.py
To enable re-use in https://github.com/pq-code-package/mlkem-c-embedded. This is applied only to the sources of pqm4 itself that are to a vast degree written by the pqm4 maintainers.
The scheme implementations plus symmetric primitives have other licenses.
@rpls, you wrote a lot of that code, could you please review if I got everything right?
@joostrijneveld, @Ko-, @cryptojedi: Parts of that code was written by you. Are you okay with dual licensing?
> Adds Apache-2.0 license in addition to CC0

- benchmarks.csv
- benchmarks.md
- crypto_kem/kyber512/m4fspeed/poly.c
- crypto_kem/kyber512/m4fstack/poly.c
- crypto_kem/kyber768/m4fspeed/kem.c
- crypto_kem/kyber768/m4fspeed/poly.c
- crypto_kem/kyber768/m4fstack/poly.c
Unfortunately, I have forgotten to include the inlining of the re-encryption in the kem.c when I updated to the NIST draft version in https://github.com/mupq/pqm4/pull/332. 
I fixed it here. This reduces the stack usage of decaps by 1 ciphertext size.
There was also a bug in the inlined re-encryption that resulted in the re-encryption always failing (but that was dead code).
> Fix inlining of Kyber re-encryption

- mk/stm32f4discovery.mk
While trying to run benchmarks for `ml-dsa-87` I noticed that it doesn't work on the `stm32f4discovery`. 
As we need 129kB of RAM, I think it's required to enable the "fullram" ld script just as for `Dilithium5` back then.
> Full ram for ml-dsa-87 on stm32f4discovery

- crypto_kem/ml-kem-512/m4fspeed/poly.c
- crypto_kem/ml-kem-512/m4fstack/poly.c
- crypto_kem/ml-kem-768/m4fspeed/poly.c
- crypto_kem/ml-kem-768/m4fstack/poly.c
This PR fixes the testvector mismatch introduced in https://github.com/mupq/pqm4/pull/244.
A bit more history.
In the PR https://github.com/mupq/pqm4/pull/128, there was the same issue. But this was identified and fixed before merging to pqm4. The problem is that the element 3329 should be mapped to 0 while packing to the public key array. In pull/128, there are two reductions: one in the NTT and one in the poly_tobytes. Due to the stack optimizations that are not described in the specification of Kyber/ML-KEM, the output of NTT should be mapped to [0, q) while packing the elements to the public key array. This remains until pull/244 removed the reduction in the NTT (and counted as a contribution of their paper). 
I encountered mismatched testvectors while generating with my own chacha20 …
> map to canonical

- crypto_kem/ml-kem-512/m4fspeed/symmetric-fips202.
- crypto_sign/ml-dsa-65/m4fstack/smalltt.h
Fixes #370.
Found with `find . -xtype l`
> Remove broken symlinks
